/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=operator-ingress/wrangler.jsonc --include-runtime=false --strict-vars=false operator-ingress/env.d.ts` (hash: 7705e77e9ca1f733ecdd1c5bb0668234)
interface __BaseEnv_Env {
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	CONNECTORS: Fetcher /* unijam-connectors-staging */ | Fetcher /* unijam-connectors-production */ | Fetcher /* unijam-connectors-development */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		CONNECTORS: Fetcher /* unijam-connectors-staging */;
	}
	interface ProductionEnv {
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		CONNECTORS: Fetcher /* unijam-connectors-production */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
